-- ============================================================
-- HE Manufacturing — Leave Portal v2 (2026-09-29) — ALREADY APPLIED to project znxtvkpnwzrzevljdsgx
-- The full SQL is stored in Supabase's migration history under these names:
--     leave_portal_v2_rules_notices_docs
--     leave_types_staff_write
-- (Dashboard → Database → Migrations, or: select statements from supabase_migrations.schema_migrations where name = '...')
--
-- What it did:
--   * hem_leave_types: rule columns (min_notice_days, late_days, doc_rule, doc labels, EN/BM notes).
--       annual 14d notice · medical: MC required, up to 2d late · hospitalization: letter required once started
--       emergency: UNPAID, up to 2d late · unpaid: 7d notice · timeoff: 3d notice
--   * hem_leave_applications: paid, doc_paths, details. Public (anon) read/insert REMOVED —
--       the portal now goes only through the functions below.
--   * hem_employees: passwords re-stored as bcrypt hashes; anon access removed.
--   * hem_leave_notices: messages to employees (approved / rejected / meeting). Staff-only table.
--   * Functions (security definer, each re-checks employee no. + password):
--       portal_data, portal_apply (enforces every rule server-side), portal_attach_docs, portal_mark_read;
--       login_employee / set_employee_password now use bcrypt.
--   * Storage bucket 'hem-leave-docs' (private, 10 MB, PDF/images): portal upload-only, staff read/delete.
-- ============================================================

-- ---- 2026-09-29 (later): migration "employee_leave_scope_entitlement" — ALREADY APPLIED ----
--   hem_employees: leave_scope ('full' | 'mc_only' | 'none'), annual_entitlement (per person), staff_type.
--   _allowed_types() / _entitlement(); portal_data lists only allowed types with the person's entitlement;
--   portal_apply refuses other types ('not_allowed') and checks balance against the person's entitlement.

-- ---- 2026-09-29 (later): migration "leave_v3_otp_superior_halfday" — ALREADY APPLIED ----
--   hem_employees: position, phone, phone_verified_at, superior_emp_no.
--   hem_phone_verify: WhatsApp verification codes (HR-only table; HR sends the code by WhatsApp).
--   portal_request_otp / portal_verify_otp; portal_apply requires a verified number, declaration +
--   typed signature; supports half day (AM/PM = 0.5 day for annual/unpaid/day-off/emergency);
--   records relief + handover; routes to the employee's superior first (stage 'superior').
--   Superior approval link: leave-approve.html?t=<token>; superior_view / superior_decide (token
--   stored as SHA-256, 21-day expiry); portal_superior_link / hr_superior_link issue fresh links.

-- ---- 2026-09-29 (later): migration "leave_v4_self_register_hod_whatsapp" — ALREADY APPLIED ----
--   WhatsApp OTP retired (portal_request_otp / portal_verify_otp no longer callable).
--   Self-service: portal_register / portal_reset — Employee ID + IC/passport (checked against
--   hem_employees.ic_hash, a SHA-256 the ERP sends; never the IC) + phone → own password (bcrypt).
--   Reset also needs the registered phone. 5 wrong tries → 15-minute lock.
--   portal_apply: HOD name + WhatsApp number required; every application starts at stage 'superior'.
--   hem_portal_settings(hr_whatsapp, hr_name): shown on leave-approve.html so the HOD can inform HR.
--   hr_portal_status(): registration status for the ERP.
